# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Main_Window.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        import sys
        import os
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(1007, 733)
        try:
            base_path = getattr(sys, '_MEIPASS', os.path.dirname(os.path.abspath(__file__)))
        except Exception:
            base_path = os.path.abspath(".")
        icon_path = os.path.join(base_path, "title.png")
        print icon_path
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(icon_path)), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setWindowOpacity(1.0)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout_5.setMargin(1)
        self.verticalLayout_5.setSpacing(3)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.widget_file_selection = QtGui.QWidget(self.centralwidget)
        self.widget_file_selection.setObjectName(_fromUtf8("widget_file_selection"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.widget_file_selection)
        self.verticalLayout_3.setMargin(1)
        self.verticalLayout_3.setSpacing(3)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.widget_local_file_selection = QtGui.QWidget(self.widget_file_selection)
        self.widget_local_file_selection.setObjectName(_fromUtf8("widget_local_file_selection"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.widget_local_file_selection)
        self.horizontalLayout_4.setMargin(1)
        self.horizontalLayout_4.setSpacing(3)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.label_new_file_path = QtGui.QLabel(self.widget_local_file_selection)
        self.label_new_file_path.setObjectName(_fromUtf8("label_new_file_path"))
        self.horizontalLayout_4.addWidget(self.label_new_file_path)
        self.lineEdit_new_file_path = QtGui.QLineEdit(self.widget_local_file_selection)
        self.lineEdit_new_file_path.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.lineEdit_new_file_path.setReadOnly(False)
        self.lineEdit_new_file_path.setObjectName(_fromUtf8("lineEdit_new_file_path"))
        self.horizontalLayout_4.addWidget(self.lineEdit_new_file_path)
        self.button_browser_file_new = QtGui.QPushButton(self.widget_local_file_selection)
        self.button_browser_file_new.setObjectName(_fromUtf8("button_browser_file_new"))
        self.horizontalLayout_4.addWidget(self.button_browser_file_new)
        self.horizontalLayout_4.setStretch(1, 1)
        self.verticalLayout_3.addWidget(self.widget_local_file_selection)
        self.widget_compare_selection = QtGui.QWidget(self.widget_file_selection)
        self.widget_compare_selection.setObjectName(_fromUtf8("widget_compare_selection"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.widget_compare_selection)
        self.horizontalLayout_3.setMargin(1)
        self.horizontalLayout_3.setSpacing(3)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.label_new_file_selection = QtGui.QLabel(self.widget_compare_selection)
        self.label_new_file_selection.setObjectName(_fromUtf8("label_new_file_selection"))
        self.horizontalLayout_3.addWidget(self.label_new_file_selection)
        self.comboBox_new_file = QtGui.QComboBox(self.widget_compare_selection)
        self.comboBox_new_file.setMaximumSize(QtCore.QSize(400, 16777215))
        self.comboBox_new_file.setObjectName(_fromUtf8("comboBox_new_file"))
        self.horizontalLayout_3.addWidget(self.comboBox_new_file)
        self.label_old_file_selection = QtGui.QLabel(self.widget_compare_selection)
        self.label_old_file_selection.setObjectName(_fromUtf8("label_old_file_selection"))
        self.horizontalLayout_3.addWidget(self.label_old_file_selection)
        self.comboBox_old_file = QtGui.QComboBox(self.widget_compare_selection)
        self.comboBox_old_file.setMaximumSize(QtCore.QSize(400, 16777215))
        self.comboBox_old_file.setObjectName(_fromUtf8("comboBox_old_file"))
        self.horizontalLayout_3.addWidget(self.comboBox_old_file)
        spacerItem = QtGui.QSpacerItem(199, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.start_compare = QtGui.QPushButton(self.widget_compare_selection)
        self.start_compare.setObjectName(_fromUtf8("start_compare"))
        self.horizontalLayout_3.addWidget(self.start_compare)
        self.horizontalLayout_3.setStretch(1, 1)
        self.horizontalLayout_3.setStretch(3, 1)
        self.verticalLayout_3.addWidget(self.widget_compare_selection)
        self.line_file = QtGui.QFrame(self.widget_file_selection)
        self.line_file.setFrameShape(QtGui.QFrame.HLine)
        self.line_file.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_file.setObjectName(_fromUtf8("line_file"))
        self.verticalLayout_3.addWidget(self.line_file)
        self.verticalLayout_5.addWidget(self.widget_file_selection)
        self.splitter_2 = QtGui.QSplitter(self.centralwidget)
        self.splitter_2.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_2.setObjectName(_fromUtf8("splitter_2"))
        self.widget_log_info = QtGui.QWidget(self.splitter_2)
        self.widget_log_info.setBaseSize(QtCore.QSize(410, 610))
        self.widget_log_info.setObjectName(_fromUtf8("widget_log_info"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.widget_log_info)
        self.verticalLayout_4.setMargin(1)
        self.verticalLayout_4.setSpacing(3)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.label_svn_info = QtGui.QLabel(self.widget_log_info)
        self.label_svn_info.setObjectName(_fromUtf8("label_svn_info"))
        self.verticalLayout_4.addWidget(self.label_svn_info)
        self.widget_log_line = QtGui.QWidget(self.widget_log_info)
        self.widget_log_line.setObjectName(_fromUtf8("widget_log_line"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.widget_log_line)
        self.horizontalLayout_2.setMargin(0)
        self.horizontalLayout_2.setSpacing(3)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.tableWidget_log_info = QtGui.QTableWidget(self.widget_log_line)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableWidget_log_info.sizePolicy().hasHeightForWidth())
        self.tableWidget_log_info.setSizePolicy(sizePolicy)
        self.tableWidget_log_info.setMinimumSize(QtCore.QSize(10, 0))
        self.tableWidget_log_info.setBaseSize(QtCore.QSize(0, 0))
        self.tableWidget_log_info.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.tableWidget_log_info.setColumnCount(4)
        self.tableWidget_log_info.setObjectName(_fromUtf8("tableWidget_log_info"))
        self.tableWidget_log_info.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        self.tableWidget_log_info.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        self.tableWidget_log_info.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        self.tableWidget_log_info.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_log_info.setHorizontalHeaderItem(3, item)
        self.tableWidget_log_info.horizontalHeader().setVisible(True)
        self.tableWidget_log_info.horizontalHeader().setCascadingSectionResizes(True)
        self.tableWidget_log_info.horizontalHeader().setSortIndicatorShown(True)
        self.tableWidget_log_info.verticalHeader().setVisible(False)
        self.tableWidget_log_info.verticalHeader().setSortIndicatorShown(False)
        self.horizontalLayout_2.addWidget(self.tableWidget_log_info)
        self.line_info_right = QtGui.QFrame(self.widget_log_line)
        self.line_info_right.setFrameShape(QtGui.QFrame.VLine)
        self.line_info_right.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_info_right.setObjectName(_fromUtf8("line_info_right"))
        self.horizontalLayout_2.addWidget(self.line_info_right)
        self.verticalLayout_4.addWidget(self.widget_log_line)
        self.verticalLayout_4.setStretch(1, 1)
        self.widget_res_tree = QtGui.QWidget(self.splitter_2)
        self.widget_res_tree.setBaseSize(QtCore.QSize(230, 601))
        self.widget_res_tree.setObjectName(_fromUtf8("widget_res_tree"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.widget_res_tree)
        self.verticalLayout_2.setMargin(1)
        self.verticalLayout_2.setSpacing(3)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.label_compare_res = QtGui.QLabel(self.widget_res_tree)
        self.label_compare_res.setObjectName(_fromUtf8("label_compare_res"))
        self.verticalLayout_2.addWidget(self.label_compare_res)
        self.widget_res_line = QtGui.QWidget(self.widget_res_tree)
        self.widget_res_line.setObjectName(_fromUtf8("widget_res_line"))
        self.gridLayout = QtGui.QGridLayout(self.widget_res_line)
        self.gridLayout.setMargin(1)
        self.gridLayout.setSpacing(3)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.label_search_item = QtGui.QLabel(self.widget_res_line)
        self.label_search_item.setObjectName(_fromUtf8("label_search_item"))
        self.gridLayout.addWidget(self.label_search_item, 0, 0, 1, 1)
        self.lineEdit_search_item = QtGui.QLineEdit(self.widget_res_line)
        self.lineEdit_search_item.setObjectName(_fromUtf8("lineEdit_search_item"))
        self.gridLayout.addWidget(self.lineEdit_search_item, 0, 1, 1, 1)
        self.button_search_item = QtGui.QPushButton(self.widget_res_line)
        self.button_search_item.setObjectName(_fromUtf8("button_search_item"))
        self.gridLayout.addWidget(self.button_search_item, 0, 2, 1, 1)
        self.line_res_tree_right = QtGui.QFrame(self.widget_res_line)
        self.line_res_tree_right.setFrameShape(QtGui.QFrame.VLine)
        self.line_res_tree_right.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_res_tree_right.setObjectName(_fromUtf8("line_res_tree_right"))
        self.gridLayout.addWidget(self.line_res_tree_right, 0, 3, 2, 1)
        self.tree_widget_res_tree = QtGui.QTreeWidget(self.widget_res_line)
        self.tree_widget_res_tree.setMinimumSize(QtCore.QSize(0, 500))
        self.tree_widget_res_tree.setLineWidth(1)
        self.tree_widget_res_tree.setAutoExpandDelay(-1)
        self.tree_widget_res_tree.setAllColumnsShowFocus(False)
        self.tree_widget_res_tree.setColumnCount(2)
        self.tree_widget_res_tree.setObjectName(_fromUtf8("tree_widget_res_tree"))
        self.tree_widget_res_tree.headerItem().setText(0, _fromUtf8("Widget Name"))
        self.tree_widget_res_tree.headerItem().setTextAlignment(0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        self.tree_widget_res_tree.headerItem().setText(1, _fromUtf8("Widget Status"))
        self.tree_widget_res_tree.headerItem().setTextAlignment(1, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        self.tree_widget_res_tree.header().setVisible(True)
        self.tree_widget_res_tree.header().setDefaultSectionSize(200)
        self.gridLayout.addWidget(self.tree_widget_res_tree, 1, 0, 1, 3)
        self.gridLayout.setColumnStretch(1, 1)
        self.gridLayout.setRowStretch(1, 1)
        self.verticalLayout_2.addWidget(self.widget_res_line)
        self.widget_res_detail = QtGui.QWidget(self.splitter_2)
        self.widget_res_detail.setBaseSize(QtCore.QSize(215, 601))
        self.widget_res_detail.setObjectName(_fromUtf8("widget_res_detail"))
        self.verticalLayout_7 = QtGui.QVBoxLayout(self.widget_res_detail)
        self.verticalLayout_7.setMargin(1)
        self.verticalLayout_7.setSpacing(3)
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.label_res_detail = QtGui.QLabel(self.widget_res_detail)
        self.label_res_detail.setObjectName(_fromUtf8("label_res_detail"))
        self.verticalLayout_7.addWidget(self.label_res_detail)
        self.splitter = QtGui.QSplitter(self.widget_res_detail)
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setObjectName(_fromUtf8("splitter"))
        self.widget_show_item = QtGui.QWidget(self.splitter)
        self.widget_show_item.setObjectName(_fromUtf8("widget_show_item"))
        self.verticalLayout = QtGui.QVBoxLayout(self.widget_show_item)
        self.verticalLayout.setMargin(0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.label_resource = QtGui.QLabel(self.widget_show_item)
        self.label_resource.setMinimumSize(QtCore.QSize(200, 200))
        self.label_resource.setAutoFillBackground(False)
        self.label_resource.setMidLineWidth(0)
        self.label_resource.setAlignment(QtCore.Qt.AlignCenter)
        self.label_resource.setObjectName(_fromUtf8("label_resource"))
        self.verticalLayout.addWidget(self.label_resource)
        self.line_seg = QtGui.QFrame(self.widget_show_item)
        self.line_seg.setFrameShape(QtGui.QFrame.HLine)
        self.line_seg.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_seg.setObjectName(_fromUtf8("line_seg"))
        self.verticalLayout.addWidget(self.line_seg)
        self.verticalLayout.setStretch(0, 1)
        self.widget_detail = QtGui.QWidget(self.splitter)
        self.widget_detail.setObjectName(_fromUtf8("widget_detail"))
        self.gridLayout_2 = QtGui.QGridLayout(self.widget_detail)
        self.gridLayout_2.setMargin(1)
        self.gridLayout_2.setSpacing(3)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.label_refer_text = QtGui.QLabel(self.widget_detail)
        self.label_refer_text.setObjectName(_fromUtf8("label_refer_text"))
        self.gridLayout_2.addWidget(self.label_refer_text, 0, 0, 1, 1)
        self.lineEdit_refer_text = QtGui.QLineEdit(self.widget_detail)
        self.lineEdit_refer_text.setObjectName(_fromUtf8("lineEdit_refer_text"))
        self.gridLayout_2.addWidget(self.lineEdit_refer_text, 0, 1, 1, 1)
        self.tree_widget_res_detail = QtGui.QTreeWidget(self.widget_detail)
        self.tree_widget_res_detail.setMinimumSize(QtCore.QSize(10, 380))
        self.tree_widget_res_detail.setColumnCount(3)
        self.tree_widget_res_detail.setObjectName(_fromUtf8("tree_widget_res_detail"))
        self.tree_widget_res_detail.headerItem().setText(0, _fromUtf8("Category"))
        self.tree_widget_res_detail.headerItem().setTextAlignment(0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        self.tree_widget_res_detail.headerItem().setTextAlignment(1, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        self.tree_widget_res_detail.headerItem().setTextAlignment(2, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        self.tree_widget_res_detail.header().setDefaultSectionSize(150)
        self.gridLayout_2.addWidget(self.tree_widget_res_detail, 1, 0, 1, 2)
        self.gridLayout_2.setColumnStretch(1, 1)
        self.gridLayout_2.setRowStretch(1, 1)
        self.verticalLayout_7.addWidget(self.splitter)
        self.verticalLayout_7.setStretch(1, 1)
        self.verticalLayout_5.addWidget(self.splitter_2)
        self.line_compare = QtGui.QFrame(self.centralwidget)
        self.line_compare.setFrameShape(QtGui.QFrame.HLine)
        self.line_compare.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_compare.setObjectName(_fromUtf8("line_compare"))
        self.verticalLayout_5.addWidget(self.line_compare)
        self.verticalLayout_5.setStretch(1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "coconut_v_1_2_by_Yves", None))
        self.label_new_file_path.setText(_translate("MainWindow", "Local File:", None))
        self.button_browser_file_new.setText(_translate("MainWindow", "Select File", None))
        self.label_new_file_selection.setText(_translate("MainWindow", "Compared File", None))
        self.label_old_file_selection.setText(_translate("MainWindow", "Control File", None))
        self.start_compare.setText(_translate("MainWindow", "Start Compare", None))
        self.label_svn_info.setText(_translate("MainWindow", "Log Info:", None))
        self.tableWidget_log_info.setSortingEnabled(True)
        item = self.tableWidget_log_info.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Revision", None))
        item = self.tableWidget_log_info.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Author", None))
        item = self.tableWidget_log_info.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Date", None))
        item = self.tableWidget_log_info.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Message", None))
        self.label_compare_res.setText(_translate("MainWindow", "Compare Result:", None))
        self.label_search_item.setText(_translate("MainWindow", "Search Widget", None))
        self.button_search_item.setText(_translate("MainWindow", "Search", None))
        self.label_res_detail.setText(_translate("MainWindow", "Widget Info:", None))
        self.label_resource.setText(_translate("MainWindow", "Show_Picture_Resource", None))
        self.label_refer_text.setText(_translate("MainWindow", "Reference", None))
        self.tree_widget_res_detail.headerItem().setText(1, _translate("MainWindow", "Control File Attribute", None))
        self.tree_widget_res_detail.headerItem().setText(2, _translate("MainWindow", "Compared File Attribute", None))

